- .travis.yml
Travis logs have a warning:
```
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
```
`xmllint` is installed by `libxml2-utils`, which fixes the warning:
```
-- Checking for modules 'gtk+-3.0;granite;libxml-2.0'
--   Found gtk+-3.0, version 3.18.9
--   Found granite, version 0.4.0.1
--   Found libxml-2.0, version 2.9.3
```
> travis: add libxml2-utils dependency

- src/CheckView.vala
This adjusts the alignment and spacing in the checkview to match granite alertview
> adjust alignment and spacing to match alertview

- README.md
We should change the listings in the README to be more generic, rather than OS-specific, since the new installer will be the standard for linux-based OSs in the future.
> Genericize all the things

- src/Application.vala
- src/DiskView/DiskView.vala
The `system-os-install` icon doesn't seem to be standardized, whereas `system-os-installer` is used by a large number of OS installers.
> Change 'system-os-install' to 'system-os-installer' to be generic

- src/Views/CheckView.vala
Fixes #92 
Seems kinda unnecessary to call out the OS here. It doesn't really add clarity imo
> Remove OS name from checkview messaging

- src/MainWindow.vala
So we can't mess up
`public` because we'll want to use these for back buttons
> Use constants for view names

- src/Views/KeyboardLayoutView.vala
* Don't use columns homogeneous
* Ellipsize really long titles
Fixes #88
> KeyboardLayoutView: Stop dialog expanding with wide titles

- src/Views/ProgressView.vala
Sets ProgressView to use the non-symbolic distributor logo by default, since that's maybe more generic and -symbolic can be set in the stylesheet.
> Use non-symbolic distributor-logo icon

- src/MainWindow.vala
In Pop GTK, the window is very narrow and tall for some reason. This appears to help ease the proportions a bit and keeps the window from being narrower than it is tall.
> Use wider width_request to help correct proportions on other stylesheets

- src/Views/LanguageView.vala
Both `Gtk.ListBox.get_selected_row ()` and `Gtk.ListBox.get_row_at_index ()` don't guarantee that the object returned will be a valid `ListBoxRow`, this caused crashes when the language list wasn't populated correctly (16.04).
> Fix segfaults in LanguageView

- src/Views/LanguageView.vala
There was a small mistake in https://github.com/elementary/installer/pull/178 with the `if` condition being in the wrong place and the installer would check if `row` is `null` twice unnecessarily. This shouldn't change how the application behaves, it's only a small optimization.
> Put the null check in it's right place

- data/application.css
- data/io.elementary.installer.gresource.xml
- meson.build
- src/Application.vala
- src/Views/ProgressView.vala
- src/meson.build
Fixes #199 
This adds an application priority stylesheet to style the Terminal. Application priority means that the system stylesheet cannot overwrite it. However, fallback priority just means it gets overwritten by `textview.view` so it doesn't really do anything meaningful as a fallback style.
If System76 wants to change this style, we can either move this into our CSS or they'll need to carry a patch for this CSS file
> Add Terminal css

- README.md
Deduplicated content that was in the README and wiki, and pointed to the wiki instead of the old Google Doc spec
> Point to the wiki

- src/Widgets/LayoutWidget.vala
Fixes #65 
We were getting a blank keyboard layout for a couple of reasons:
1. The last arguments to `gkbd_drawing.render` were DPI not scale factor, it looks like they are hardcoded to 50 when using the dialog version of this widget, so do the same: https://github.com/GNOME/libgnomekbd/blob/master/libgnomekbd/gkbd-keyboard-drawing.c#L1542
2. The Vala compiler is doing something to that array and passing it in a format that `libgnomekbd` doesn't want. I re-wrote it to be how I'd expect it to work in C and it seems to have fixed it, but it's not pretty. If anyone knows how better to translate that to Vala without the keyboard disappearing again or it crashing, be my guest.
> Fix blank keyboard widget

- src/MainWindow.vala
- src/Views/CheckView.vala
Adds a timeout function which monitors requirements and switches to the check view when
requirements are not met. Clicking Ignore will ignore future requirement checks. This
will allow the user to simply plug their laptop in to get the view to automatically
switch back to the view that they were on.
Closes #250, closes #251
> Make the check view automatic

- src/Views/ProgressView.vala
Fixes an issue that causes the installer to crash after the `Installer.install()` method is used, due to `install()` taking ownership of `disks`, then Vala also trying to free it.
> Fix double free of Disks pointer

- src/Helpers/LogHelper.vala
- src/Views/ProgressView.vala
Closes #227
- Makes a change to how the log buffer is handled. Concatenating text to the buffer directly causes the text view to reset, losing the scrolled position. Instead, using the `insert` method on the buffer allows the existing text contents to be retained, and new contents inserted at the end.
- The terminal button will now automatically scroll to the bottom of the view when the inner text view is updated, and the view was previously at the bottom.
> Implement Better Terminal Behavior

- .travis.yml
Avoids random Travis failures.
> Travis: Use vala-lint container from Docker Hub

- README.md
It was moved from the system76 organization to the pop-os organization
> Update link to distinst

- src/Views/DiskView.vala
One-liner; helps prevent the view from growing, plus makes it more consistent with the other views.
> Shorten disk title and change to title case

- src/Widgets/DecryptMenu.vala
- Changes to a more dialog-style layout
- Adds an icon + overlay to show it's a locked disk
- Adds some explanatory copy
- Moves the placeholder text out to labels
- Changes "Physical Volume" to "Device name"
- Sets a default physical volume name to `data`
- Adds a suggested action class to the button
- Sets the button to insensitive by default
| `master` | `decrypt-popover` |
|------------|-------------------------|
| ![screenshot from 2018-04-23 10 10 47](https://user-images.githubusercontent.com/611168/39139313-cdd55f02-46de-11e8-9576-1278de8c39d8.png) | ![screenshot from 2018-04-23 11 04 50](https://user-images.githubusercontent.com/611168/39141917-60cdd0da-46e6-11e8-82d7-185fcff9f0ce.png) |
| ![screenshot from 2018-04-23 10 10 …
> Rework decrypt menu UI

- src/Widgets/PartitionBar.vala
Sets a tooltip of the partition's path to aid in picking the right one among many similar partitions. Fixes #315.
> Set partition tooltips

- src/Views/EncryptView.vala
Cherry picked from #350 
This makes it so activating entries in the encrypt view (by pressing the enter key for example), also activates the next button
> EncryptView: activate next button when activating entries

- src/Views/KeyboardLayoutView.vala
- src/Views/LanguageView.vala
- src/Widgets/VariantWidget.vala
Fixes #279 
Activates the next button when the variant widget is activated (either by double click or enter).
Single click activate is turned off here because after selecting a layout you may want to test your selection, so you don't necessarily want to change screens right after you make a selection
> Activate next button on variant widget enter

- src/MainWindow.vala
Fixes funky styling and a Gtk warning.
We never used the `os-installer` class and Pop has forked anyways so :man_shrugging:
> MainWindow: Use Gtk.Window instead of Dialog

- data/application.css
The Terminal CSS is now upstream in the stylesheet. Styles for `.primary` need to be added since this is no longer a dialog subclass
> application.css: Remove terminal class and add primary

- src/MainWindow.vala
- src/Views/ErrorView.vala
- src/Widgets/Terminal.vala
Fixes #386 
Redesigns this view to be more like what we see in https://github.com/elementary/granite/blob/master/lib/Widgets/MessageDialog.vala
Updates some properties of the terminal widget to match the dialog
> ErrorView: Redesign Terminal

- src/Views/TryInstallView.vala
We don't need this now that we run the panel in the installer session
> TryInstallView: remove shutdown button

- debian/io.elementary.installer-session.postrm
- debian/io.elementary.installer-session.preinst
This reverts commit d0a297cc251d2a35c87efcbe80f2c958545f858d.
Shouldn't be necessary now after https://github.com/elementary/onboarding/commit/36f0777b7823e214acf75aab67ed9c56471c0931
> Revert "session: divert undesirable autostart"

- debian/io.elementary.installer.install
This should be merged with #407 to prevent package build failures about the policy not existing anymore.
> deb-packaging: Don't install policy

- data/installer.desktop
Makes the installer session work under the new version of `gnome-session` without setting up any systemd stuff yet. This will prevent the installer session from running on anything older than GNOME 3.34, but we can always take this bit out manually if we're testing on `bionic` for example.
> Use --builtin for installer session

- src/Views/AbstractInstallerView.vala
In our new version of vala, abstract classes can't have public constructors anymore.
> AbstractInstallerView: make constructor protected

- data/installer.session
The installer package installs the desktop file for the greeter compositor (since it doesn't have one), and it gets renamed to `io.elementary.installer.compositor.desktop` , the component name in `RequiredComponents` has to match.
I think this is the cause of the installer session crashing.
> Make compositor component name match desktop

- data/autostart.desktop
Fixes the issue where we weren't seeing any disks to install to.
When we created an autostart desktop, we didn't copy the `Exec` line from the actual working desktop file.
> Autostart installer with pkexec

- src/Config.vala.in
- src/Helpers/KeyboardLayoutHelper.vala
- src/meson.build
PR on behalf of mutual interest from mercode OS and NixOS.
This has been a problem for us in NixOS for gnome-desktop [0] and other projects.
See aforementioned issue for more details.
cc @mkg20001
[0]: https://gitlab.gnome.org/GNOME/gnome-desktop/issues/130
> Honor XKB_CONFIG_ROOT environment variable, don't hardcode

- meson.build
find_library prefixes everything with lib automatically.
On certain platforms this will result in an error like
```
meson.build:19:0: ERROR: C library 'libgnomekbdui' not found
```
> build: use find_library correctly

- src/Views/CheckView.vala
I've just been helping diagnose some install failures on a daily iso from November and it turned out to be an issue with installing into a VM with a 10GiB virtual hard disk. It resulted in a fairly useless "unsquashfs failed" error that didn't indicate it was an out of space issue at all (which is probably a separate issue for distinst).
Once we bumped up the size of the disk image, the final installed size of the system was only 7.7GB, so would have fitted in the 10GiB disk image but there obviously needs to be a bit of a buffer to extract and then clean up afterwards.
We now know that even 10GiB is not enough for the 6.0 daily install to succeed, so lets bump this up to 15GB to at least give people a warning that the install might fail if they have less than that.
> CheckView: Bump minimum free space to 15GB

- data/installer.session
I haven't tested this but I believe it will work in conjunction with https://github.com/elementary/default-settings/pull/186/ to ensure the installer session presents itself with the correct XDG_CURRENT_DESKTOP name to pick up the correct GSettings overrides.
> Set XDG_CURRENT_DESKTOP to Pantheon

- src/Views/ProgressView.vala
This is the first part of the fixes for #457 
I've tested that this fixes boot failures on UEFI systems installed using the "Clean Install" option with encryption enabled. It works by creating an extra unencrypted `/boot` mount point for the kernel and initramfs files.
This will not help with a custom install option where you're installing into an existing encrypted volume.
> Create a /boot mount point if we're using encryption

- common/DBusStructures.vala
- common/meson.build
- daemon/Application.vala
- daemon/Daemon.vala
- daemon/io.elementary.InstallerDaemon.conf
- daemon/io.elementary.InstallerDaemon.service
- daemon/meson.build
- meson.build
- src/Helpers/InstallerDaemon.vala
- src/Helpers/LogHelper.vala
- src/MainWindow.vala
- src/Objects/Configuration.vala
- src/Objects/Mount.vala
- src/Utils.vala
- src/Views/CheckView.vala
- src/Views/DiskView.vala
- src/Views/KeyboardLayoutView.vala
- src/Views/PartitioningView.vala
- src/Views/ProgressView.vala
- src/Widgets/DecryptMenu.vala
- src/Widgets/PartitionBar.vala
- src/Widgets/PartitionMenu.vala
- src/meson.build
Requires deb packaging branch: #479 
This looks like quite a scary diff, but it's largely just moving things out of the current installer process into a new daemon and then adding the necessary structures to communicate with it over DBus.
I've tested BIOS and UEFI installs with this branch, with both custom and default partitioning and all is working well.
The only thing this changes functionally is some of the hangs in the GUI where Distinst was doing stuff on the GUI thread. So things feel a little more responsive, especially around disk selection and partitioning now.
This doesn't yet make the necessary changes to have the GUI run as a standard user. I'll follow up with that in a separate branch as this one is getting kind of long.
It would be good to get this merged sooner rather than …
> Split into GUI and Daemon

- src/Helpers/LocaleHelper.vala
Passing a string with a newline on the end of it was upsetting something and causing it to regenerate locales for all the things and take forever.
> Strip locale string

- data/installer-default-settings.gschema.override
- data/installer.session
- data/meson.build
Fixes #477 
Requires deb-packaging PR: #485 
After some more consideration, we still need to keep the separate installer session. The installer itself can run fine as a standard user (so in theory it could run in the greeter). However, it still calls on gparted to do disk partitioning, which would need root permissions, which we wouldn't be able to get in the greeter.
So the best way to solve the current theming issues in the installer session is to ship a subset of the GSettings overrides in the installer package.
> Add a minimal set of GSettings overrides

- daemon/Daemon.vala
Fixes #489 
We were missing a case for BIOS systems and trying to align the LVM on BIOS systems to the EFI partition which clearly didn't exist. So this adds that missing case.
> Fix partition positioning for BIOS systems without encryption

- data/autostart.desktop
Decoupling this from #486 since it's mostly unrelated.
Fixes #253 
I've tested that you can still install successfully with these changes
> Remove pkexec from autostart file

- src/MainWindow.vala
Fixes #501 
The current code only checks the system requirements after selecting a disk. Meaning you get stuck on the disk selection page with no explanation why the button to install onto your lone 12 GB disk is disabled.
This moves the check one step earlier, so you get an error saying there are no disks big enough first.
> Check requirements before disk selection

- daemon/Daemon.vala
Distinst has an `on_error` callback, but it seems not all errors are sent via that. Getting nonzero return codes catches the rest and allows us to show the error screen in cases like #517
> daemon: catch additional distinst errors

- daemon/Daemon.vala
When we're probing for potential disks to install to, we don't care about read-only drives (CD/DVD drives, etc), so lets skip over those.
> daemon: Skip read-only drives in disk probe

- src/MainWindow.vala
- src/Views/TryInstallView.vala
- src/Widgets/InstallTypeGrid.vala
Fixes #515 
* Remove redundant label in the title area. We don't use a label like this in the other preceding views
* Use radio buttons to make it obvious where the selection is, and very clear what the current selection is
* Incorporate some string changes from #510 
* Lots of code style and organizational cleanups
> TryInstallView: Rewrite as radiobuttons, code style

- src/Views/TryInstallView.vala
- src/Widgets/InstallTypeGrid.vala
* Don't wrap title label, this preserves extra space
* Add max_width_chars to subtitle to force the wrap
>  TryInstallView: stop view from vexpanding the window

- src/Views/ErrorView.vala
* Stop the error view from expanding the window
* Fix margins
* Use fun cute icons instead of boring bullets. And don't translate the bullets lol
* code style
> ErrorView: modern code style, fix expanding window

- src/Views/TryInstallView.vala
Fixes an issue where clicking one selection and then clicking another selection would connect multiple times to the same button. Instead, we have one connection and check which radio is active when the button is clicked
> TryInstallView: Don't repeatedly connect signals

- debian/control
OS builds are failing because the installer can't be installed.
> Debian control: Point to RDNN greeter dependency

- src/Views/EncryptView.vala
We can't use this for the password entry yet because Granite.ValidatedEntry doesn't have a concept of a warning state
> EncryptView: Use Granite.ValidatedEntry

- src/Utils.vala
Fixes #600 
I've tested this method behaves as expected by passing it some valid and invalid hostnames and logging results to the console. So this should be a quick fix to any invalid hostnames that are being generated on various bits of hardware that are producing weird results for the automatic logic.
> Fallback when generated hostname is invalid

- src/Views/CheckView.vala
This fixes the string always showing in English regardless of the selected language
> CheckView: Fix wrong gettext syntax

- src/MainWindow.vala
- src/Views/CheckView.vala
Currently, if you go from powered to battery we throw you from wherever you were into the CheckView to warn you about installing on battery power. This branch throws an infobar covering the beginning of the action area instead.
The reasoning behind the placement here is to making sure you can still complete the language view if this is shown on startup. Another alternative would be waiting to throw the infobar until after you've completed the language view and then we could show it in the more traditional top aligned location
> MainWindow: throw an infobar on battery

- src/Views/CheckView.vala
> CheckView: warn about daily builds

- src/Views/CheckView.vala
"Ignore" is kind of ambiguous. It tells us what will happen to this view, but it doesn't tell us what happens if we ignore. We have [precedent](https://github.com/search?q=org:elementary+anyway&type=code) for "[Action] Anyway" in these kinds of warnings which I think is more explicit about what you're agreeing to do when you ignore the warning
> CheckView: Ignore → Install Anyway

- src/Helpers/InstallerDaemon.vala
This is done so that on some systems, particularly the older ones, the installer fails to continue in `Custom Install` due to not showing ALL partitions.
> Increase DBUS_TIMEOUT_MSEC variable

- debian/control
Not sure if should be depends instead? Goes with #711
> Control: Add espeak to depends

- src/Application.vala
`window_position = Gtk.WindowPosition.CENTER_ALWAYS` makes window unresizable and instead moves it to bottom right corner trying to center it.
> Don't center the window

- src/Views/DriversView.vala
Updates copy based on discussion in #723. Also try to be more specific, combine license agreement with checkbutton
> DriversView: update copy and recommend internet connection

- .github/workflows/ci.yml
CI is already run on every pull request there's no reason to run lint or build after merging something into main
> CI: don't run on main

- data/installer-default-settings.gschema.override
Removes old settings keys that don't exist anymore
> Settings Overrides: Remove old keys

- data/disk-bar-fallback.css
- src/Widgets/DiskBar.vala
- src/Widgets/PartitionBar.vala
- src/Widgets/PartitionMenu.vala
* Use Gtk.Gesture instead of EventBox with button press event
* GObject style as much as possible
* Reduce the number of public properties, especially since `partition` is already a construction property
* Remove dead code
* Add a simple icon property instead of other classes changing this classes widget children
* clarify a couple property names
* Code style
> PartitionBar: cleanup and code style

- data/installer.desktop
I believe this is the cause of the crashes in the live session in the daily ISOs.
I haven't looked to see if we also need to do some systemd stuff as well as this, but removing this from the ISO at least makes the crashing stop.
> Remove builtin flag from installer session

- meson.build
- src/Views/KeyboardLayoutView.vala
- src/Widgets/PartitionBar.vala
Fixes #763
Closes #767 
I can't actually get the menu to popup in this branch or any previous commit since the last release, but this makes sure the gesture sends the event at least. Maybe the menu only works in an actual installer session for some reason?
> PartitionBar: make sure we get click events

- src/Widgets/VariantWidget.vala
Based on changes from:
- https://github.com/elementary/initial-setup/pull/174/files
- https://github.com/elementary/initial-setup/pull/134/files#diff-c8863692580f666c84bfe20b6e708e218ec13598a4756ea0f13828d3189b9650
* Code style
* Variant title wraps instead of truncates
* use child property
* Prepare for CenterBox
> VariantWidget: Gtk4 prep

- data/disk-bar-fallback.css
- src/Widgets/DiskBar.vala
Fixes #691
Also Gtk4 prep:
* Set size of elements in CSS
* Lay out vertically
* Use Granite.HeaderLabel
* Replace grids with boxes
* Code style
* Make legend item clickable anywhere on the item
* Don't use Granite style class that doens't exist in GTK 4
> Diskbar: responsive redesign

- src/Views/LanguageView.vala
- src/Views/SuccessView.vala
- src/Widgets/DecryptMenu.vala
- src/Widgets/DiskGrid.vala
- src/Widgets/InstallTypeGrid.vala
There is no more PRIMARY class in Gtk4, so use H3 instead since that's the closest thing
Also fix an instance where we weren't using a constant at all
> Gtk4 Prep: don't use primary label

- src/Views/ErrorView.vala
Build this button in a way that still works in GTK 4
> ErrorView: prep details button for Gtk4

- po/POTFILES
- src/Views/PartitioningView.vala
- src/Widgets/DiskBar.vala
- src/Widgets/PartitionBlock.vala
- src/Widgets/PartitionMenu.vala
- src/meson.build
* Make it clearer that this is not the whole bar that contains all of the partitions
* Make it a Bin subclass since it only contains one widget
* Remove some unnecessary expands
> Widgets: Rename PartitionBar to PartitionBlock

- src/Views/PartitioningView.vala
Fixes #692 
Adds some dummy partition data when running in test mode
> PartitioningView: add test disk/partition data

- src/Views/PartitioningView.vala
- src/Widgets/DiskBar.vala
Dry some stuff and simplify construction args
> Diskbar: construct with InstallerDaemon.Disk

- src/Views/PartitioningView.vala
- src/Widgets/DiskBar.vala
- src/Widgets/PartitionBlock.vala
Moves the menu up to partitionview so we're not passing it through two objects
> PartitionBlock: GObject

- data/io.elementary.installer.desktop.in
Fixes #806 
confirmed that this command works on latest RC
> Launcher: use dbus to log out

- src/Widgets/PartitionMenu.vala
Also make sure we're updating icon and add warning text for invalid custom value while we're here
> PartitionMenu: write check_values as single function with early returns

- src/HostnameValidator.vala
- test/HostnameValidatorTest.vala
- test/Test.vala
- test/meson.build
HostnameValidator.vala:
- Add comments inline and separate lines so we know exactly what each line tests for
- Use `has_prefix` and `has_suffix`
HostnameValidatorTest:
- Give this test a unique name for CI
- Make the test one file
- Fix path syntax in meson
- Add comments so we know what each line tests for
- Make sure we test for all of the things that the function should be checking, notably empty hostname and a super long hostname with otherwise short labelsni
> HostnameValidatorTest: cleanup, comments, more tests

- src/Views/CheckView.vala
message_box.get_first_child without parenthesis is the address of the function and therefore will never be null.
> CheckView: Actually check if a children is there

- src/Application.vala
Fixes #775
gettext doesn't give us translations if `LANG` is set to `C.UTF-8` (which it is initially on the ISO)
If we initially set this to English, gettext initializes properly and then we can correctly change the language at runtime with the `LANGUAGE` variable after that.
> Set LANG variable on startup

- data/installer.metainfo.xml.in
- src/Views/KeyboardLayoutView.vala
- src/Views/LanguageView.vala
- src/Widgets/VariantWidget.vala
Fixes #745 
Replace deprecated Adw.Leaflet with Adw.NavigationView
> VariantWidget: Leaflet → NavigationView

- .github/workflows/ci.yml
- README.md
- data/installer.metainfo.xml.in
- meson.build
- src/MainWindow.vala
- src/meson.build
Fixes #758 
Not sure if things exist in Greeter for this to work, but does what we can from Installer's POV
> MainWindow: center with pantheon protocol

- src/Views/EncryptView.vala
> EncryptView: use single view

- src/Views/PartitioningView.vala
- src/Widgets/DiskBar.vala
- src/Widgets/PartitionBlock.vala
- src/Widgets/PartitionMenu.vala
Fixes #848 
Turns out the GTK constraint solver crashes (unpredictably? not always) when you give it invalid constraints, so I've made multiple improvements here to make the code clearer and remove most (all?) of the possibilities where we could be passing invalid constraints.
The main issue was clamping the percentages between 1% and 99%. Imagine a case where a disk has 3 partitions and the first two partitions use <1% of the disk and the 3rd partition uses >99%. We then clamp these percentages to `[1, 1, 99]`, which according to my calculations adds up to 101%. This makes the GTK constraint solver sad.
- Add a more complicated mock disk layout to the test data in `PartitioningView.vala`, this allows reproducing the crashing issue in #848 prior to the other changes, and should help test …
> fix(DiskBar): simplify and prevent invalid constraints

- debian/control
This PR allows building the installer on all architectures.
Related to elementary/os#754. Tested on ARM64 server.
> debian: allow all architectures

- src/Widgets/InstallTypeGrid.vala
* Make sure the screen reader reads this as a Radio not a checkbox
* Changes the order from Title → Subtitle →  "Radio button" to Title → "Radio button (not) selected" → Subtitle. Makes it so you don't have to listen to the whole subtitle to know the selection status
> InstallTypeGrid: improve screenreader labeling

- src/Widgets/DiskGrid.vala
* Make sure that this is read as a radio not a checkbox
* Buttons are completely unlabeled in main for some reason. Make sure we set labels
> DiskGrid: improve screen reader labels

- src/Views/EncryptView.vala
- src/Widgets/DescriptionRow.vala
Makes messages able to be navigated and read by the screen reader. Also add a key controller so that you can still start typing right away to fill in your encryption password without having to manually focus the entry first
> EncryptView: make warnings messages screen reader accessible
