CMakeLists.txt, src/DiskView/DiskGrid.vala, src/DiskView/DiskView.vala, src/LanguageView.vala, src/Objects/Disk.vala, src/Objects/Partition.vala, src/Objects/PartitionTable.vala, src/Objects/org.freedesktop.udisks2.vala, src/Utils.vala
This separates a little bit the widgets from the disk objects.
=> Reorganize the project and create real structure to hold data

src/LanguageView.vala, src/MainWindow.vala
=> Add cancel button at language select time

CMakeLists.txt, src/LanguageView.vala, src/Views/AbstractInstallerView.vala
So we don't have to keep re-setting the action area etc
=> Add AbstractInstallerView

CMakeLists.txt, README.md
=> RDNN project name and binary

CMakeLists.txt, src/MainWindow.vala, src/Views/AbstractInstallerView.vala, src/Views/KeyboardLayoutView.vala
Clean up mainwindow a little bit then add a keyboard layout view with dummy listbox contents for testing
=> Keyboard layout view

CMakeLists.txt, src/MainWindow.vala, src/Views/DiskView.vala, src/Views/ProgressView.vala
This adds a prototype for the progress view. It doesn't actually use any real data and the vte is currently represented by a frame
=> Add progress view prototype

src/MainWindow.vala, src/Views/KeyboardLayoutView.vala, src/Views/LanguageView.vala
We can't cancel before selecting language and layout settings
=> Remove cancel buttons from first two steps

src/Views/LanguageView.vala
=> Re-layout language view

src/Views/DiskView.vala
Makes DiskView a subclass of AbstractInstallerView and removes all the stuff that we're not using yet
=> Remove extra bits from diskview

src/MainWindow.vala
=> Set dialog title to OS release

CMakeLists.txt, src/MainWindow.vala, src/Views/SuccessView.vala
=> Add Success View

src/MainWindow.vala, src/Views/AbstractInstallerView.vala, src/Views/DiskView.vala, src/Views/TryInstallView.vala
=> Add a property cancellable to AbstractInstallerView and use it

src/Views/CheckView.vala
=> Wrap title and description text for checkview

src/MainWindow.vala
=> make view stack names match their variable names

src/Views/LanguageView.vala
=> LanguageView: Remove frame halign

CMakeLists.txt, src/MainWindow.vala, src/Views/ErrorView.vala
Just like the success view. Could probably use some Pango love.
=> Error view

src/MainWindow.vala, src/Views/TryInstallView.vala
* Add some extra margin
* Remove some unnecessary properties
Before:
After:
=> Make window fixed size and adjust tryview

src/MainWindow.vala, src/Views/AbstractInstallerView.vala
=> connect cancel signal in abstract installer view

src/Views/KeyboardLayoutView.vala
Adds an entry to allow the user to type and test that the keyboard layout is correct. Fixes #96
=> Adds an entry to test the keyboard layout.

data/io.elementary.installer.desktop.in, src/MainWindow.vala
=> Set icon name for the window

src/Views/TryInstallView.vala
=> Re-language to Demo mode

CMakeLists.txt
=> Add en_US as an available locale

src/MainWindow.vala, src/Views/AbstractInstallerView.vala, src/Views/CheckView.vala
=> Make cancel go back to try view

src/Views/KeyboardLayoutView.vala, src/Views/LanguageView.vala, src/Views/TryInstallView.vala
=> Add Back Buttons and change Next to Select

CMakeLists.txt, src/Dialogs/EndSessionDialog.vala, src/Views/TryInstallView.vala
To confirm your end session choices before we just kill your session
=> Add end session dialog

src/Utils.vala, src/Views/TryInstallView.vala
=> Add guest session switcher button

src/Views/SuccessView.vala
=> Shutdown after 30s on success

src/Views/SuccessView.vala
=> Restart after timeout instead of shut down

src/Views/ErrorView.vala
=> Change session button to working demo button

src/Utils.vala, src/Views/ErrorView.vala, src/Views/TryInstallView.vala
=> Use a singleton for SeatInterface

data/io.elementary.installer.desktop.in, data/io.elementary.installer.policy, data/meson.build
=> Execute with pkexec

src/Widgets/VariantWidget.vala
=> VariantWidget.vala: can't pass null to gtk.label

src/Views/SuccessView.vala
Fixes #217. I kept the name of the OS in there for clarity, but would also be fine with removing it.
=> Remove the "OS has been installed"

src/Views/CheckView.vala
Ready for review. Handles Issue Detection for #219.
=> Move issue detection to side-by-side

src/Views/TryInstallView.vala
For #219. Not 100% sold on the icons, but full-color icons felt too heavy there.
This design will also better accommodate #202
=> Side by side Try or Install

src/Objects/Configuration.vala, src/Views/EncryptView.vala, src/Views/ProgressView.vala
This PR includes https://github.com/elementary/installer/pull/214
It implements encryption support on UEFI systems using distinst, and the password provided through the new encryption screens.
=> Encryption support

src/Views/ProgressView.vala
=> Fix disk API stuff

src/MainWindow.vala, src/Views/ErrorView.vala, src/Views/ProgressView.vala
Adds a log view in the same fashion as it is done in `ProgressView`.
Closes #179
=> Logs on error view

src/Application.vala, src/Helpers/Inhibitor.vala, src/Views/AbstractInstallerView.vala, src/Views/ErrorView.vala, src/Views/ProgressView.vala
Tiny cleanup of the last PR plus other linting issues
=> Happy Linter, Happy Life

src/Views/DiskView.vala, src/Widgets/DiskGrid.vala
Addresses https://github.com/elementary/installer/issues/219
=> Side by side disks

src/Views/ProgressView.vala
This will enable encryption when installing on a BIOS system.
=> Add swap and enable encryption on BIOS

src/Views/ProgressView.vala
This runs through each distinst step, feeding fake progress into the progress view
=> Add fake status when in test mode

src/Dialogs/EndSessionDialog.vala
Teeny tiny deprecation annoyance.
=> Fix margin deprecation

src/Objects/Configuration.vala, src/Objects/Mount.vala, src/Utils.vala, src/Views/DiskView.vala, src/Views/ProgressView.vala, src/meson.build
This is an upstreaming of changes from @mmstick and the pop fork, which gets the installer building again and sets up a lot of the logic needed for the partitioning screen.
=> Update Disks logic

src/Views/SuccessView.vala
As seen at https://github.com/pop-os/installer/pull/32#issuecomment-378768060. This makes it easier for downstream to remove the first line while not losing translations.
=> Update success labels from Dan's copy

.editorconfig, src/Config.vala.in
Added .editorconfig file (like at https://github.com/elementary/code/pull/372) and linted the project. Fixed indentation in the config.
=> Add .editorconfig

src/MainWindow.vala, src/Views/EncryptView.vala
Main question here is the buttons in the Encrypt view. Right now the back button is kind of awkward. See https://youtu.be/hIH5Ng6w-qE
Fixes #295; see that issue for more context.
=> Encrypt after disks

README.md, data/disk-bar-fallback.css, data/io.elementary.installer.gresource.xml, src/Application.vala, src/MainWindow.vala, src/Objects/Mount.vala, src/Views/DiskView.vala, src/Views/PartitioningView.vala, src/Widgets/DecryptMenu.vala, src/Widgets/DiskBar.vala, src/Widgets/DiskGrid.vala, src/Widgets/PartitionBar.vala, src/Widgets/PartitionMenu.vala, src/meson.build
Brings the PartitioningView and related widgets by @mmstick upstream :tada:
=> Upstream PartitioningView

src/Views/PartitioningView.vala
This variable is never used so :man_shrugging:
=> PartitionView: Remove unused variable

src/Widgets/DiskBar.vala
* Don't use methods for things we only do once, then reduce variable scope
* Use Grids instead of Boxes
* Use Style constants where possible
* Fix missing unused bar
=> DiskBar: fix unused bar and misc cleanup

README.md
Just some small revisions to bring it up to date.
=> Revise run and debug directions in README

src/Widgets/DecryptMenu.vala
=> Simplify decryption copy

src/Views/ProgressView.vala
Fix from https://github.com/pop-os/installer/commit/2465445028bb3f790c6cc8e59914d77aa6a2aedb#diff-7f3d8e5ce9f904691e38db036917dbe9L362
=> Fix distinst breaking change

debian/control
Make sure we depend on gparted since this is used by the custom partition view
=> Depend on gparted

src/Views/ProgressView.vala
From https://github.com/pop-os/installer/pull/114/commits/e6472ae03d97ee45469354ce6daf689134785067
=> Upstream fix language selection issue

src/Views/DiskView.vala, src/Views/PartitioningView.vala, src/Widgets/PartitionBar.vala
Fixes broken builds due to changes in distinst
=> Distinst string → utf8 changes

src/Application.vala
=> Remove extra space

src/Helpers/LogHelper.vala
=> LogHelper.vala: fix some code style issues

src/Views/DiskView.vala, src/Views/PartitioningView.vala
Distinst API change to eliminate a raw pointer.
=> Fix contains_mount

src/Helpers/LogHelper.vala, src/MainWindow.vala, src/Views/CheckView.vala, src/Views/DiskView.vala, src/Views/KeyboardLayoutView.vala, src/Views/ProgressView.vala
Didn't bother with fixing the linting errors in udisks2, as udisks2 has long since been removed.
Requires #341 to fix all errors on master
=> Fix linting errors

src/Objects/Mount.vala, src/Views/PartitioningView.vala, src/Widgets/PartitionMenu.vala
- Ensure that the EFI partition is large enough
- Check that key mounts have a valid file system
- Return errors so that the UI can display the errors
=> Perform additional mount validation checks

src/Views/EncryptView.vala
The icons used in Pop!_OS's fork of the installer.
=> Drive Encryption Icons

src/Widgets/InstallTypeGrid.vala
=> Fix deprecated margin_right

src/Application.vala, src/Objects/Mount.vala, src/Utils.vala, src/Views/ProgressView.vala, src/Widgets/PartitionBar.vala, src/Widgets/PartitionMenu.vala
=> Fix builds

src/Views/ProgressView.vala
fixes #377 
Not intelligent, but better than "todo"
=> ProgressView: change hostname to elementary-os

src/Views/KeyboardLayoutView.vala
From https://github.com/elementary/initial-setup/pull/42/commits/c7f634125fca32692d7221ec540cb7988a23f79e
=> KeyboardLayoutView Suggestions from Corentin

data/meson.build, data/wingpanel-installer.desktop
=> Add an installer autostart for the panel

data/icons/tach-slow-symbolic.svg, data/io.elementary.installer.gresource.xml, src/Application.vala, src/Views/EncryptView.vala
=> Replace system monitor with tach-slow

data/installer.session
=> Session: Swap gala for greeter compositor

src/Views/EncryptView.vala
=> EncryptView: Revise copy

data/gsd/org.gnome.SettingsDaemon.MediaKeys-installer.desktop, data/gsd/org.gnome.SettingsDaemon.Power-installer.desktop, data/gsd/org.gnome.SettingsDaemon.XSettings-installer.desktop, data/meson.build
=> Install required GSD autostarts

src/Config.vala.in, src/Helpers/KeyboardLayoutHelper.vala, src/Helpers/LocaleHelper.vala, src/meson.build
Depends on https://github.com/elementary/installer/pull/432
=> build: don't hardcode isocodes path

src/Views/KeyboardLayoutView.vala
Fixes #437 
Uses GSettings to set the selected keyboard layout in the session, so that when you type in the "test your layout" box, you get the expected result.
Also makes the preview work with the selected layout instead of the layout stored in `Configuration` which is only save when you press "Next" and go past the keyboard layout configuration.
=> Set selected keyboard layout in current session

src/Helpers/LocaleHelper.vala, src/Views/LanguageView.vala
This _should_ make the chosen language be picked up by the guest (demo) session and hence fix (in theory) #442 .
I haven't been able to test on an installed system however as I can't get my guest session working at all.
=> Set chosen language as default locale

daemon/Daemon.vala, src/Helpers/InstallerDaemon.vala, src/Views/LanguageView.vala
We need root privileges to write to this file, so we need to move this code into the daemon.
=> Set demo mode locale in daemon

data/io.elementary.installer.desktop.in
I've tested this still works in an iso
=> Remove pkexec requirement for GUI

debian/io.elementary.installer-session.install
To go with https://github.com/elementary/installer/pull/484
=> installer-session: Install GSettings overrides

src/MainWindow.vala
Fixes #496 
Remove deletable while we're here since we don't pack window controls anymore
=> MainWindow: Ask WM to CENTER_ALWAYS

debian/lightdm.conf
To go with https://github.com/elementary/installer/pull/486
=> Disable LightDM autologin

src/Views/EncryptView.vala
also reduce `INFO_LABEL_CHARS` and hexpand instead to avoid forcing the window larger
=> EncryptView: Use modern codestyle

src/Widgets/DiskGrid.vala, src/Widgets/InstallTypeGrid.vala
=> Match radiobuttons in try/install and choose disk

.github/workflows/ci.yml
Only run the CI build action on PRs
=> Actions: Only run CI on PR

data/io.elementary.installer.desktop.in
=> Make desktop launcher logout

src/Views/ProgressView.vala
=> ProgressView: Use fileicon for avatar

data/ProgressView.css
=> ProgressView: Update shadow to match background timing

data/installer.appdata.xml.in, meson.build
#604 is the one we want here for an ISO respin
=> Release 1.0.2

data/installer.appdata.xml.in, meson.build
=> Release 1.0.4

daemon/Daemon.vala, data/installer.appdata.xml.in
=> Daemon: double encrypted boot size

src/Views/CheckView.vala
Fixes #639 
Only add whichever lines are relevant:
=> CheckView: rewrite as a single page

src/Application.vala, src/MainWindow.vala
Same as https://github.com/elementary/initial-setup/pull/148
Fixes #491
=> Allow MainWindow to be resized

src/MainWindow.vala, src/Views/CheckView.vala
Show this view whenever there are messages in the list. Better than checking individual variables like this because we don't have to update it every time this view changes
=> CheckView: show when messagebox has children

src/MainWindow.vala, src/Views/CheckView.vala
We already check disk size in the DiskView so I'm not sure why we'd do that twice
=> CheckView: remove minimum space check

src/MainWindow.vala, src/Objects/Configuration.vala, src/Views/DiskView.vala, src/Views/DriversView.vala, src/Views/PartitioningView.vala, src/Views/ProgressView.vala, src/meson.build
=> Add an option to install proprietary drivers

src/Views/EncryptView.vala
=> Fix size of icon in Encrypt View

src/Views/EncryptView.vala
* Can't subclass Revealer
* GObject style and code style while we're here
* Using Style class to set label size
* Fix property access
=> EncryptView: ErrorRevealer Gtk4 prep

src/Views/DriversView.vala
Because this feature moves from AppCenter to System Settings in OS 8
=> DriversView: Update driver installation instruction

data/io.elementary.installer.desktop.in
Fixes #806
Closes #820
Sounds like this solution still isn't working for some folks, but this one should for sure work? It works in a VM here at least
=> Launcher: use gnome-session-quit --no-prompt
